'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import { Cake } from '@/lib/types';
import WhatsAppButton from './WhatsAppButton';

interface OrderFormData {
  customerName: string;
  customerPhone: string;
  deliveryAddress: string;
  deliveryPincode: string;
  quantity: number;
  messageOnCake: string;
  preferredTime: string;
}

interface Props {
  cake: Cake;
}

export default function OrderForm({ cake }: Props) {
  const [orderPlaced, setOrderPlaced] = useState(false);
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<OrderFormData>();

  const onSubmit = (data: OrderFormData) => {
    // Validate pincode
    const allowedPincodes = process.env.NEXT_PUBLIC_CITY_PINCODES?.split(',') || [];
    if (!allowedPincodes.includes(data.deliveryPincode)) {
      alert(`Sorry, we only deliver to ${process.env.NEXT_PUBLIC_CITY_NAME} area.`);
      return;
    }

    setOrderPlaced(true);
    
    // Store order in Firebase (optional - for admin panel)
    // WhatsApp message will be generated by WhatsAppButton component
  };

  if (orderPlaced) {
    return (
      <div className="text-center py-8">
        <h2 className="text-2xl font-bold text-green-600 mb-4">Order Request Submitted!</h2>
        <p className="text-gray-600 mb-4">
          Please click the WhatsApp button below to confirm your order details.
        </p>
        <WhatsAppButton
          cake={cake}
          orderData={{}}
          isCustom={false}
        />
      </div>
    );
  }

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Your Name *</label>
        <input
          {...register('customerName', { required: true })}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
        />
        {errors.customerName && <span className="text-red-500 text-sm">Required</span>}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Phone Number *</label>
        <input
          {...register('customerPhone', { required: true, pattern: /^[0-9]{10}$/ })}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
          placeholder="9876543210"
        />
        {errors.customerPhone && <span className="text-red-500 text-sm">Valid 10-digit number required</span>}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Delivery Address *</label>
        <textarea
          {...register('deliveryAddress', { required: true })}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
          rows={3}
        />
        {errors.deliveryAddress && <span className="text-red-500 text-sm">Required</span>}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Pincode *</label>
        <input
          {...register('deliveryPincode', { required: true })}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
          placeholder={process.env.NEXT_PUBLIC_CITY_PINCODES?.split(',')[0]}
        />
        {errors.deliveryPincode && <span className="text-red-500 text-sm">Required</span>}
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
        <input
          type="number"
          {...register('quantity', { required: true, min: 1, max: 10 })}
          defaultValue={1}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Message on Cake</label>
        <input
          {...register('messageOnCake')}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
          placeholder="Happy Birthday!"
        />
      </div>

      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Preferred Delivery Time</label>
        <select
          {...register('preferredTime')}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-pink-500"
        >
          <option value="10:00-12:00">10:00 AM - 12:00 PM</option>
          <option value="12:00-14:00">12:00 PM - 2:00 PM</option>
          <option value="14:00-16:00">2:00 PM - 4:00 PM</option>
          <option value="16:00-18:00">4:00 PM - 6:00 PM</option>
          <option value="18:00-20:00">6:00 PM - 8:00 PM</option>
        </select>
      </div>

      <button
        type="submit"
        className="w-full bg-pink-600 text-white py-3 rounded-lg font-semibold hover:bg-pink-700 transition"
      >
        Place Order via WhatsApp
      </button>
    </form>
  );
}
